"""Generate the fixture that keeps the browser and the server honest.

Two implementations of the same maths now exist: Python on the server, TypeScript
in the browser. If they drift, the app coaches a player toward one number while
the server gates them on another. This writes a set of frames plus the values
Python computes for them; the vitest suite in web/ asserts TypeScript agrees.

    python scripts/make_crosscheck_fixture.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.core.enums import Side  # noqa: E402
from app.data.exercises import EXERCISES_BY_KEY  # noqa: E402
from app.services.pose.analyzer import analyze_set  # noqa: E402
from app.services.pose.geometry import Frame, compute_metrics, openness  # noqa: E402
from tests.factories import squat_trace  # noqa: E402

OUT = ROOT / "web" / "src" / "pose" / "__fixtures__" / "crosscheck.json"

#: A portrait phone video, so the aspect-ratio handling is exercised too.
ASPECT = 1080 / 1920
EXERCISE = "single_leg_squat"
SIDE = Side.LEFT


def main() -> None:
    exercise = EXERCISES_BY_KEY[EXERCISE]
    rule = exercise.rule
    assert rule is not None

    # Build the pose in isotropic space, then squash x the way a portrait camera
    # does, so the fixture holds exactly what a browser would receive.
    #
    # The factory centres the body on x=0.5, which is right for a square image.
    # In a portrait frame the isotropic x axis only runs 0..aspect, so the centre
    # is aspect/2 — without this shift the virtual player's feet land outside the
    # picture and the "are you fully in shot" check quite correctly rejects every
    # frame. Shifting x is a translation, so no angle changes.
    x_shift = ASPECT / 2 - 0.5
    source = squat_trace(reps=4, peak_flexion=82.0, valgus_shift=0.03, seconds_per_rep=3.0)
    wire_frames = []
    frames = []
    for f in source:
        landmarks = [
            {
                "x": round((float(x) + x_shift) / ASPECT, 9),
                "y": round(float(y), 9),
                "z": round(float(z) / ASPECT, 9),
                "visibility": round(float(v), 4),
            }
            for (x, y, z), v in zip(f.xyz, f.vis, strict=True)
        ]
        wire_frames.append({"t": round(f.t, 6), "landmarks": landmarks})
        frames.append(Frame.from_payload(f.t, landmarks, aspect=ASPECT))

    metric_keys = [
        "knee_flexion",
        "hip_flexion",
        "knee_extension",
        "trunk_lean",
        "knee_valgus",
        "pelvic_drop",
        "ankle_dorsiflexion",
        "heel_raise_ratio",
        "stance_width_ratio",
    ]
    per_frame = []
    for f in frames:
        metrics = compute_metrics(f, SIDE, use_z=bool(rule.use_z))
        per_frame.append({k: metrics[k] for k in metric_keys if k in metrics})

    analysis = analyze_set(frames, rule, SIDE)

    payload = {
        "_comment": (
            "Generated by scripts/make_crosscheck_fixture.py — do not edit by hand. "
            "Regenerate whenever app/services/pose changes."
        ),
        "exercise_key": EXERCISE,
        "side": SIDE.value,
        "aspect": ASPECT,
        "rule": rule.model_dump(mode="json"),
        "frames": wire_frames,
        "expected": {
            "per_frame_metrics": per_frame,
            "openness": [round(openness(f), 6) for f in frames],
            "completed_reps": analysis.completed_reps,
            "valid_reps": analysis.valid_reps,
            "form_score": analysis.form_score,
            "reps": [
                {
                    "index": r.index,
                    "duration": r.duration,
                    "is_valid": r.is_valid,
                    "form_score": r.form_score,
                    "metrics": r.metrics,
                    "violation_codes": sorted(v.code for v in r.violations),
                }
                for r in analysis.reps
            ],
        },
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=1, ensure_ascii=False), encoding="utf-8")
    size_kb = OUT.stat().st_size / 1024
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(frames)} frames, {size_kb:.0f} KB)")
    print(f"  reps {analysis.completed_reps}, valid {analysis.valid_reps}, "
          f"score {analysis.form_score}")

    _write_side_on(x_shift)


def _write_side_on(x_shift: float) -> None:
    """The same movement filmed from the side — what the app must refuse.

    This reproduces the real failure a test video exposed: footage shot side-on
    when the exercise needs a head-on view. Generated rather than recorded, so
    the test does not depend on a file existing.
    """
    out = OUT.with_name("side-on.json")
    source = squat_trace(reps=4, peak_flexion=82.0, seconds_per_rep=3.0, sagittal_axis="x")
    frames = [
        {
            "t": round(f.t, 6),
            "landmarks": [
                {
                    "x": round((float(x) + x_shift) / ASPECT, 9),
                    "y": round(float(y), 9),
                    "z": round(float(z) / ASPECT, 9),
                    "visibility": round(float(v), 4),
                }
                for (x, y, z), v in zip(f.xyz, f.vis, strict=True)
            ],
        }
        for f in source
    ]
    out.write_text(
        json.dumps(
            {
                "_comment": "Side-on footage of a front-view exercise. Must be refused.",
                "aspect": ASPECT,
                "frames": frames,
            }
        ),
        encoding="utf-8",
    )
    print(f"wrote {out.relative_to(ROOT)}  ({len(frames)} frames, "
          f"{out.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
