"""Bake a copy of the exercise library into the front end as demo insurance.

If the backend is not running the app still has something to score against. This
is generated, never hand-written, so app/data/exercises.py stays the one place
the library is authored. Regenerate whenever it changes:

    python scripts/make_fallback_exercises.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app.data.exercises import EXERCISES  # noqa: E402

OUT = ROOT / "web" / "src" / "fallback.ts"


def main() -> None:
    payload = [
        {
            "id": index,
            "key": e.key,
            "name_en": e.name_en,
            "name_th": e.name_th,
            "category": e.category,
            "cue_en": e.cue_en,
            "cue_th": e.cue_th,
            "equipment": e.equipment,
            "demo_url": e.demo_url,
            "pose_rule": e.rule.model_dump(mode="json") if e.rule else None,
        }
        for index, e in enumerate(EXERCISES, start=1)
        if e.rule is not None
    ]

    body = json.dumps(payload, indent=2, ensure_ascii=False)
    OUT.write_text(
        "/* GENERATED by scripts/make_fallback_exercises.py — do not edit.\n"
        " *\n"
        " * A copy of the camera-scored exercises, so the demo still runs if the\n"
        " * backend is down. The backend is still the source of truth: when it is\n"
        " * reachable the app fetches from it and ignores this file entirely.\n"
        " */\n"
        "import type { Exercise } from './pose/rules';\n\n"
        f"export const FALLBACK_EXERCISES: Exercise[] = {body} as unknown as Exercise[];\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(payload)} exercises, "
          f"{OUT.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
