/* GENERATED by scripts/make_fallback_exercises.py — do not edit.
 *
 * A copy of the camera-scored exercises, so the demo still runs if the
 * backend is down. The backend is still the source of truth: when it is
 * reachable the app fetches from it and ignores this file entirely.
 */
import type { Exercise } from './pose/rules';

export const FALLBACK_EXERCISES: Exercise[] = [
  {
    "id": 1,
    "key": "isometric_quad_set",
    "name_en": "Isometric quadriceps set",
    "name_th": "เกร็งกล้ามเนื้อต้นขาด้านหน้าค้างไว้",
    "category": "activation",
    "cue_en": "Press the back of the knee down and hold. Keep the leg straight.",
    "cue_th": "กดหลังเข่าลงกับพื้นแล้วค้างไว้ เหยียดขาให้ตรง",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "hold",
      "view": "side",
      "enforce_view": true,
      "space": "image",
      "use_z": false,
      "detection": null,
      "targets": [
        {
          "metric": "knee_flexion",
          "aggregate": "peak",
          "min": null,
          "max": 8.0,
          "tolerance": 2.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "knee_not_straight",
          "message_en": "Straighten the knee fully.",
          "message_th": "เหยียดเข่าให้สุด"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": null,
      "tempo_max_s": null,
      "hold_target_s": 10.0,
      "emit": [
        {
          "metric": "knee_flexion",
          "as_key": "pose.knee_extension_lag",
          "rep_aggregate": "peak",
          "set_aggregate": "median",
          "unit": "deg"
        }
      ]
    }
  },
  {
    "id": 2,
    "key": "glute_bridge",
    "name_en": "Double-leg glute bridge",
    "name_th": "ยกสะโพกสองขา",
    "category": "activation",
    "cue_en": "Drive through the heels, squeeze the glutes at the top.",
    "cue_th": "ดันส้นเท้าลง บีบก้นตอนอยู่จุดสูงสุด",
    "equipment": null,
    "demo_url": "/demos/glute_bridge.mp4",
    "pose_rule": {
      "mode": "rep",
      "view": "side",
      "enforce_view": true,
      "space": "image",
      "use_z": false,
      "detection": {
        "signal": "hip_extension",
        "enter": -38.0,
        "exit": -44.0,
        "min_duration_s": 0.35,
        "max_duration_s": 20.0,
        "min_amplitude": 6.0
      },
      "targets": [
        {
          "metric": "hip_flexion",
          "aggregate": "min",
          "min": null,
          "max": 34.0,
          "tolerance": 5.0,
          "weight": 1.5,
          "critical": false,
          "judge": "worst",
          "code": "hip_not_extended",
          "message_en": "Push the hips higher until the body is in one line.",
          "message_th": "ยกสะโพกให้สูงจนลำตัวเป็นเส้นตรง"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": 0.8,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": [
        {
          "metric": "hip_flexion",
          "as_key": "pose.bridge_hip_extension",
          "rep_aggregate": "min",
          "set_aggregate": "median",
          "unit": "deg"
        }
      ]
    }
  },
  {
    "id": 3,
    "key": "heel_slide",
    "name_en": "Heel slide (knee ROM)",
    "name_th": "ไถส้นเท้าเพื่อเพิ่มมุมงอเข่า",
    "category": "mobility",
    "cue_en": "Slide the heel towards the buttock as far as pain allows.",
    "cue_th": "ไถส้นเท้าเข้าหาก้นเท่าที่ไม่เจ็บ",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "rep",
      "view": "side",
      "enforce_view": true,
      "space": "image",
      "use_z": false,
      "detection": {
        "signal": "knee_flexion",
        "enter": 30.0,
        "exit": 15.0,
        "min_duration_s": 0.35,
        "max_duration_s": 20.0,
        "min_amplitude": 20.0
      },
      "targets": [
        {
          "metric": "knee_flexion",
          "aggregate": "peak",
          "min": 90.0,
          "max": null,
          "tolerance": 10.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "rom_limited",
          "message_en": "Aim for more knee bend.",
          "message_th": "พยายามงอเข่าให้มากขึ้น"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": null,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": [
        {
          "metric": "knee_flexion",
          "as_key": "pose.knee_flexion_rom",
          "rep_aggregate": "peak",
          "set_aggregate": "max",
          "unit": "deg"
        }
      ]
    }
  },
  {
    "id": 4,
    "key": "ankle_knee_to_wall",
    "name_en": "Knee-to-wall ankle mobility",
    "name_th": "ดันเข่าชนกำแพง (เพิ่มมุมกระดกข้อเท้า)",
    "category": "mobility",
    "cue_en": "Keep the heel flat, drive the knee forward over the toes.",
    "cue_th": "ส้นเท้าติดพื้น ดันเข่าไปข้างหน้าผ่านปลายเท้า",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "rep",
      "view": "side",
      "enforce_view": true,
      "space": "image",
      "use_z": false,
      "detection": {
        "signal": "ankle_dorsiflexion",
        "enter": 10.0,
        "exit": 3.0,
        "min_duration_s": 0.35,
        "max_duration_s": 20.0,
        "min_amplitude": 6.0
      },
      "targets": [
        {
          "metric": "ankle_dorsiflexion",
          "aggregate": "peak",
          "min": 30.0,
          "max": null,
          "tolerance": 4.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "dorsiflexion_limited",
          "message_en": "Push the knee further forward without lifting the heel.",
          "message_th": "ดันเข่าไปข้างหน้าอีก โดยส้นเท้าห้ามยก"
        },
        {
          "metric": "heel_raise_ratio",
          "aggregate": "peak",
          "min": null,
          "max": 0.12,
          "tolerance": 0.0,
          "weight": 1.5,
          "critical": true,
          "judge": "worst",
          "code": "heel_lifted",
          "message_en": "Heel came off the floor — that does not count.",
          "message_th": "ส้นเท้ายกขึ้น ครั้งนี้ไม่นับ"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": null,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": [
        {
          "metric": "ankle_dorsiflexion",
          "as_key": "pose.ankle_dorsiflexion",
          "rep_aggregate": "peak",
          "set_aggregate": "max",
          "unit": "deg"
        }
      ]
    }
  },
  {
    "id": 5,
    "key": "prone_hamstring_curl",
    "name_en": "Prone hamstring curl",
    "name_th": "งอเข่าท่านอนคว่ำ",
    "category": "strength",
    "cue_en": "Curl the heel up slowly, keep the hips on the floor.",
    "cue_th": "งอเข่ายกส้นเท้าขึ้นช้าๆ สะโพกแนบพื้น",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "rep",
      "view": "side",
      "enforce_view": true,
      "space": "image",
      "use_z": false,
      "detection": {
        "signal": "knee_flexion",
        "enter": 30.0,
        "exit": 15.0,
        "min_duration_s": 0.35,
        "max_duration_s": 20.0,
        "min_amplitude": 30.0
      },
      "targets": [
        {
          "metric": "knee_flexion",
          "aggregate": "peak",
          "min": 90.0,
          "max": null,
          "tolerance": 10.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "rom_limited",
          "message_en": "Bring the heel closer to the glute.",
          "message_th": "งอเข่าให้ส้นเท้าเข้าใกล้ก้นมากขึ้น"
        },
        {
          "metric": "hip_flexion",
          "aggregate": "peak",
          "min": null,
          "max": 20.0,
          "tolerance": 5.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "hip_hitch",
          "message_en": "Hips are lifting — keep them down.",
          "message_th": "สะโพกยกขึ้น กดสะโพกให้แนบพื้น"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": 1.5,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": [
        {
          "metric": "knee_flexion",
          "as_key": "pose.knee_flexion_rom",
          "rep_aggregate": "peak",
          "set_aggregate": "max",
          "unit": "deg"
        }
      ]
    }
  },
  {
    "id": 6,
    "key": "side_lying_hip_abduction",
    "name_en": "Side-lying hip abduction",
    "name_th": "นอนตะแคงกางสะโพก",
    "category": "activation",
    "cue_en": "Lift the top leg without rolling the hips back.",
    "cue_th": "ยกขาบนขึ้น อย่าให้สะโพกหมุนไปข้างหลัง",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "rep",
      "view": "front",
      "enforce_view": true,
      "space": "image",
      "use_z": true,
      "detection": {
        "signal": "hip_flexion",
        "enter": 15.0,
        "exit": 7.0,
        "min_duration_s": 0.35,
        "max_duration_s": 20.0,
        "min_amplitude": 12.0
      },
      "targets": [
        {
          "metric": "hip_flexion",
          "aggregate": "peak",
          "min": 30.0,
          "max": null,
          "tolerance": 5.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "rom_limited",
          "message_en": "Lift the leg a little higher.",
          "message_th": "ยกขาให้สูงขึ้นอีกนิด"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": null,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": []
    }
  },
  {
    "id": 7,
    "key": "double_leg_calf_raise",
    "name_en": "Double-leg calf raise",
    "name_th": "เขย่งปลายเท้าสองขา",
    "category": "strength",
    "cue_en": "Rise as high as you can, lower under control.",
    "cue_th": "เขย่งขึ้นให้สูงที่สุด แล้วลงช้าๆ",
    "equipment": null,
    "demo_url": "/demos/double_leg_calf_raise.mp4",
    "pose_rule": {
      "mode": "rep",
      "view": "side",
      "enforce_view": true,
      "space": "image",
      "use_z": false,
      "detection": {
        "signal": "heel_raise_ratio",
        "enter": 0.17,
        "exit": 0.12,
        "min_duration_s": 0.35,
        "max_duration_s": 20.0,
        "min_amplitude": 0.05
      },
      "targets": [
        {
          "metric": "heel_raise_ratio",
          "aggregate": "peak",
          "min": 0.42,
          "max": null,
          "tolerance": 0.05,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "raise_too_low",
          "message_en": "Get up higher onto the toes.",
          "message_th": "เขย่งให้สูงกว่านี้"
        },
        {
          "metric": "knee_flexion",
          "aggregate": "peak",
          "min": null,
          "max": 15.0,
          "tolerance": 4.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "knee_bend",
          "message_en": "Keep the knees straight.",
          "message_th": "เหยียดเข่าให้ตรง"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": 0.6,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": []
    }
  },
  {
    "id": 8,
    "key": "single_leg_balance",
    "name_en": "Single-leg balance",
    "name_th": "ยืนขาเดียวทรงตัว",
    "category": "activation",
    "cue_en": "Stand tall on one leg, keep the pelvis level.",
    "cue_th": "ยืนขาเดียวให้ตัวตรง รักษาระดับเชิงกราน",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "hold",
      "view": "front",
      "enforce_view": true,
      "space": "image",
      "use_z": true,
      "detection": null,
      "targets": [
        {
          "metric": "pelvic_drop",
          "aggregate": "peak",
          "min": null,
          "max": 5.0,
          "tolerance": 1.5,
          "weight": 1.5,
          "critical": false,
          "judge": "worst",
          "code": "pelvic_drop",
          "message_en": "Hip is dropping on the other side — keep the pelvis level.",
          "message_th": "สะโพกอีกข้างตก พยายามรักษาระดับเชิงกรานให้ตรง"
        },
        {
          "metric": "trunk_lean",
          "aggregate": "peak",
          "min": null,
          "max": 8.0,
          "tolerance": 3.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "trunk_lean",
          "message_en": "Too much lean — keep the chest up.",
          "message_th": "ลำตัวเอนมากเกินไป ยกอกขึ้น"
        },
        {
          "metric": "knee_valgus",
          "aggregate": "peak",
          "min": null,
          "max": 8.0,
          "tolerance": 2.0,
          "weight": 2.0,
          "critical": false,
          "judge": "worst",
          "code": "knee_valgus",
          "message_en": "Knee is collapsing inward — push it out over the middle toes.",
          "message_th": "เข่าบิดเข้าด้านใน ดันเข่าออกให้อยู่แนวนิ้วเท้ากลาง"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": null,
      "tempo_max_s": null,
      "hold_target_s": 30.0,
      "emit": [
        {
          "metric": "pelvic_drop",
          "as_key": "pose.balance_pelvic_drop",
          "rep_aggregate": "peak",
          "set_aggregate": "median",
          "unit": "deg"
        }
      ]
    }
  },
  {
    "id": 9,
    "key": "single_leg_squat",
    "name_en": "Single-leg squat",
    "name_th": "สควอทขาเดียว",
    "category": "strength",
    "cue_en": "Sit back and down on one leg. Knee tracks over the middle toes.",
    "cue_th": "ย่อลงบนขาเดียว ให้เข่าอยู่แนวนิ้วเท้ากลาง",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "rep",
      "view": "front",
      "enforce_view": true,
      "space": "image",
      "use_z": true,
      "detection": {
        "signal": "knee_flexion",
        "enter": 30.0,
        "exit": 15.0,
        "min_duration_s": 0.35,
        "max_duration_s": 20.0,
        "min_amplitude": 20.0
      },
      "targets": [
        {
          "metric": "knee_flexion",
          "aggregate": "peak",
          "min": 60.0,
          "max": null,
          "tolerance": 5.0,
          "weight": 1.5,
          "critical": false,
          "judge": "worst",
          "code": "depth_insufficient",
          "message_en": "Go deeper — aim for 60 degrees of knee bend.",
          "message_th": "ย่อให้ลึกขึ้น เป้าหมายงอเข่า 60 องศา"
        },
        {
          "metric": "knee_valgus",
          "aggregate": "peak",
          "min": null,
          "max": 8.0,
          "tolerance": 2.0,
          "weight": 2.0,
          "critical": true,
          "judge": "worst",
          "code": "knee_valgus",
          "message_en": "Knee is collapsing inward — push it out over the middle toes.",
          "message_th": "เข่าบิดเข้าด้านใน ดันเข่าออกให้อยู่แนวนิ้วเท้ากลาง"
        },
        {
          "metric": "pelvic_drop",
          "aggregate": "peak",
          "min": null,
          "max": 5.0,
          "tolerance": 1.5,
          "weight": 1.5,
          "critical": false,
          "judge": "worst",
          "code": "pelvic_drop",
          "message_en": "Hip is dropping on the other side — keep the pelvis level.",
          "message_th": "สะโพกอีกข้างตก พยายามรักษาระดับเชิงกรานให้ตรง"
        },
        {
          "metric": "trunk_lean",
          "aggregate": "peak",
          "min": null,
          "max": 15.0,
          "tolerance": 3.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "trunk_lean",
          "message_en": "Too much lean — keep the chest up.",
          "message_th": "ลำตัวเอนมากเกินไป ยกอกขึ้น"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": 1.5,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": [
        {
          "metric": "knee_flexion",
          "as_key": "pose.slsq_knee_flexion",
          "rep_aggregate": "peak",
          "set_aggregate": "median",
          "unit": "deg"
        },
        {
          "metric": "knee_valgus",
          "as_key": "pose.slsq_knee_valgus",
          "rep_aggregate": "peak",
          "set_aggregate": "median",
          "unit": "deg"
        },
        {
          "metric": "pelvic_drop",
          "as_key": "pose.slsq_pelvic_drop",
          "rep_aggregate": "peak",
          "set_aggregate": "median",
          "unit": "deg"
        }
      ]
    }
  },
  {
    "id": 10,
    "key": "split_squat",
    "name_en": "Split squat",
    "name_th": "สควอทท่าแยกขา",
    "category": "strength",
    "cue_en": "Drop the back knee straight down, front shin close to vertical.",
    "cue_th": "ย่อเข่าหลังลงตรงๆ หน้าแข้งขาหน้าเกือบตั้งฉาก",
    "equipment": null,
    "demo_url": "/demos/split_squat.mp4",
    "pose_rule": {
      "mode": "rep",
      "view": "front",
      "enforce_view": true,
      "space": "image",
      "use_z": true,
      "detection": {
        "signal": "knee_flexion",
        "enter": 55.0,
        "exit": 40.0,
        "min_duration_s": 0.35,
        "max_duration_s": 20.0,
        "min_amplitude": 10.0
      },
      "targets": [
        {
          "metric": "knee_flexion",
          "aggregate": "peak",
          "min": 80.0,
          "max": null,
          "tolerance": 8.0,
          "weight": 1.0,
          "critical": false,
          "judge": "best",
          "code": "depth_insufficient",
          "message_en": "Go deeper on the front leg.",
          "message_th": "ย่อขาหน้าให้ลึกขึ้น"
        },
        {
          "metric": "knee_valgus",
          "aggregate": "peak",
          "min": null,
          "max": 10.0,
          "tolerance": 2.0,
          "weight": 2.0,
          "critical": true,
          "judge": "worst",
          "code": "knee_valgus",
          "message_en": "Knee is collapsing inward — push it out over the middle toes.",
          "message_th": "เข่าบิดเข้าด้านใน ดันเข่าออกให้อยู่แนวนิ้วเท้ากลาง"
        },
        {
          "metric": "trunk_lean",
          "aggregate": "peak",
          "min": null,
          "max": 20.0,
          "tolerance": 3.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "trunk_lean",
          "message_en": "Too much lean — keep the chest up.",
          "message_th": "ลำตัวเอนมากเกินไป ยกอกขึ้น"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": 0.8,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": []
    }
  },
  {
    "id": 11,
    "key": "nordic_hamstring_curl",
    "name_en": "Nordic hamstring curl",
    "name_th": "นอร์ดิกแฮมสตริง",
    "category": "strength",
    "cue_en": "Lower as slowly as you can with the hips locked straight.",
    "cue_th": "ลดตัวลงช้าที่สุด สะโพกเหยียดตรงตลอด",
    "equipment": "partner or anchor for the ankles",
    "demo_url": null,
    "pose_rule": {
      "mode": "rep",
      "view": "side",
      "enforce_view": true,
      "space": "image",
      "use_z": false,
      "detection": {
        "signal": "trunk_lean",
        "enter": 20.0,
        "exit": 8.0,
        "min_duration_s": 0.35,
        "max_duration_s": 20.0,
        "min_amplitude": 20.0
      },
      "targets": [
        {
          "metric": "trunk_lean",
          "aggregate": "peak",
          "min": 45.0,
          "max": null,
          "tolerance": 5.0,
          "weight": 1.5,
          "critical": false,
          "judge": "worst",
          "code": "break_point_early",
          "message_en": "Try to hold on further before letting go.",
          "message_th": "พยายามควบคุมให้ลงได้ไกลกว่านี้"
        },
        {
          "metric": "hip_flexion",
          "aggregate": "peak",
          "min": null,
          "max": 15.0,
          "tolerance": 5.0,
          "weight": 2.0,
          "critical": true,
          "judge": "worst",
          "code": "hip_hinge",
          "message_en": "You are folding at the hips — keep hips and shoulders in one line.",
          "message_th": "งอที่สะโพก ให้สะโพกกับไหล่อยู่ในเส้นเดียวกัน"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": 2.5,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": [
        {
          "metric": "trunk_lean",
          "as_key": "pose.nordic_break_angle",
          "rep_aggregate": "peak",
          "set_aggregate": "max",
          "unit": "deg"
        }
      ]
    }
  },
  {
    "id": 12,
    "key": "single_leg_rdl",
    "name_en": "Single-leg Romanian deadlift",
    "name_th": "ดันสะโพกขาเดียว (RDL)",
    "category": "strength",
    "cue_en": "Hinge at the hip, back flat, free leg in line with the body.",
    "cue_th": "พับที่สะโพก หลังตรง ขาลอยอยู่แนวเดียวกับลำตัว",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "rep",
      "view": "side",
      "enforce_view": true,
      "space": "image",
      "use_z": false,
      "detection": {
        "signal": "hip_flexion",
        "enter": 30.0,
        "exit": 15.0,
        "min_duration_s": 0.35,
        "max_duration_s": 20.0,
        "min_amplitude": 25.0
      },
      "targets": [
        {
          "metric": "hip_flexion",
          "aggregate": "peak",
          "min": 70.0,
          "max": null,
          "tolerance": 8.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "hinge_shallow",
          "message_en": "Hinge further forward.",
          "message_th": "พับสะโพกลงให้มากขึ้น"
        },
        {
          "metric": "knee_flexion",
          "aggregate": "peak",
          "min": null,
          "max": 30.0,
          "tolerance": 6.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "knee_bend_excess",
          "message_en": "That is turning into a squat — keep the knee soft, not bent.",
          "message_th": "กลายเป็นสควอท ให้เข่างอเล็กน้อยพอ"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": 2.0,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": [
        {
          "metric": "hip_flexion",
          "as_key": "pose.rdl_hip_hinge",
          "rep_aggregate": "peak",
          "set_aggregate": "median",
          "unit": "deg"
        }
      ]
    }
  },
  {
    "id": 13,
    "key": "single_leg_calf_raise",
    "name_en": "Single-leg calf raise",
    "name_th": "เขย่งปลายเท้าขาเดียว",
    "category": "strength",
    "cue_en": "Full height every rep, lower slowly.",
    "cue_th": "เขย่งให้สุดทุกครั้ง ลงช้าๆ",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "rep",
      "view": "side",
      "enforce_view": true,
      "space": "image",
      "use_z": false,
      "detection": {
        "signal": "heel_raise_ratio",
        "enter": 0.17,
        "exit": 0.12,
        "min_duration_s": 0.35,
        "max_duration_s": 20.0,
        "min_amplitude": 0.05
      },
      "targets": [
        {
          "metric": "heel_raise_ratio",
          "aggregate": "peak",
          "min": 0.45,
          "max": null,
          "tolerance": 0.05,
          "weight": 1.5,
          "critical": true,
          "judge": "worst",
          "code": "raise_too_low",
          "message_en": "Not high enough — that rep does not count.",
          "message_th": "เขย่งไม่สูงพอ ครั้งนี้ไม่นับ"
        },
        {
          "metric": "knee_flexion",
          "aggregate": "peak",
          "min": null,
          "max": 15.0,
          "tolerance": 4.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "knee_bend",
          "message_en": "Keep the knee straight.",
          "message_th": "เหยียดเข่าให้ตรง"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": 0.6,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": [
        {
          "metric": "heel_raise_ratio",
          "as_key": "pose.calf_raise_height",
          "rep_aggregate": "peak",
          "set_aggregate": "median",
          "unit": "ratio"
        }
      ]
    }
  },
  {
    "id": 14,
    "key": "copenhagen_plank",
    "name_en": "Copenhagen adduction plank",
    "name_th": "โคเปนเฮเกนแพลงก์ (กล้ามเนื้อขาหนีบ)",
    "category": "strength",
    "cue_en": "Top leg on the bench, lift the hips until the body is one straight line.",
    "cue_th": "วางขาบนบนม้านั่ง ยกสะโพกจนลำตัวเป็นเส้นตรง",
    "equipment": "bench or partner",
    "demo_url": null,
    "pose_rule": {
      "mode": "hold",
      "view": "front",
      "enforce_view": true,
      "space": "image",
      "use_z": true,
      "detection": null,
      "targets": [
        {
          "metric": "trunk_lean",
          "aggregate": "mean",
          "min": 60.0,
          "max": 120.0,
          "tolerance": 10.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "body_not_horizontal",
          "message_en": "Keep the body horizontal.",
          "message_th": "รักษาลำตัวให้ขนานกับพื้น"
        },
        {
          "metric": "hip_flexion",
          "aggregate": "peak",
          "min": null,
          "max": 20.0,
          "tolerance": 6.0,
          "weight": 1.5,
          "critical": false,
          "judge": "worst",
          "code": "hip_sag",
          "message_en": "Hips are sagging — lift them back into line.",
          "message_th": "สะโพกตก ยกขึ้นให้เป็นเส้นตรง"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": null,
      "tempo_max_s": null,
      "hold_target_s": 20.0,
      "emit": [
        {
          "metric": "hold_seconds",
          "as_key": "pose.copenhagen_hold",
          "rep_aggregate": "max",
          "set_aggregate": "max",
          "unit": "s"
        }
      ]
    }
  },
  {
    "id": 15,
    "key": "wall_sit",
    "name_en": "Wall sit",
    "name_th": "นั่งพิงกำแพง",
    "category": "strength",
    "cue_en": "Thighs parallel to the floor, back flat on the wall.",
    "cue_th": "ต้นขาขนานพื้น หลังแนบกำแพง",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "hold",
      "view": "side",
      "enforce_view": true,
      "space": "image",
      "use_z": false,
      "detection": null,
      "targets": [
        {
          "metric": "knee_flexion",
          "aggregate": "mean",
          "min": 80.0,
          "max": 110.0,
          "tolerance": 8.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "knee_angle_off",
          "message_en": "Aim for about 90 degrees at the knee.",
          "message_th": "ให้มุมเข่าประมาณ 90 องศา"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": null,
      "tempo_max_s": null,
      "hold_target_s": 45.0,
      "emit": []
    }
  },
  {
    "id": 16,
    "key": "step_down",
    "name_en": "Lateral step-down",
    "name_th": "ก้าวลงจากกล่องด้านข้าง",
    "category": "strength",
    "cue_en": "Lower slowly until the other heel taps the floor.",
    "cue_th": "ย่อลงช้าๆ จนส้นเท้าอีกข้างแตะพื้น",
    "equipment": "step / box 20-30cm",
    "demo_url": null,
    "pose_rule": {
      "mode": "rep",
      "view": "front",
      "enforce_view": true,
      "space": "image",
      "use_z": true,
      "detection": {
        "signal": "knee_flexion",
        "enter": 25.0,
        "exit": 12.0,
        "min_duration_s": 0.35,
        "max_duration_s": 20.0,
        "min_amplitude": 18.0
      },
      "targets": [
        {
          "metric": "knee_flexion",
          "aggregate": "peak",
          "min": 50.0,
          "max": null,
          "tolerance": 6.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "depth_insufficient",
          "message_en": "Lower a little further.",
          "message_th": "ย่อลงให้ลึกขึ้นอีกนิด"
        },
        {
          "metric": "knee_valgus",
          "aggregate": "peak",
          "min": null,
          "max": 8.0,
          "tolerance": 2.0,
          "weight": 2.0,
          "critical": true,
          "judge": "worst",
          "code": "knee_valgus",
          "message_en": "Knee is collapsing inward — push it out over the middle toes.",
          "message_th": "เข่าบิดเข้าด้านใน ดันเข่าออกให้อยู่แนวนิ้วเท้ากลาง"
        },
        {
          "metric": "pelvic_drop",
          "aggregate": "peak",
          "min": null,
          "max": 6.0,
          "tolerance": 1.5,
          "weight": 1.5,
          "critical": false,
          "judge": "worst",
          "code": "pelvic_drop",
          "message_en": "Hip is dropping on the other side — keep the pelvis level.",
          "message_th": "สะโพกอีกข้างตก พยายามรักษาระดับเชิงกรานให้ตรง"
        },
        {
          "metric": "trunk_lean",
          "aggregate": "peak",
          "min": null,
          "max": 20.0,
          "tolerance": 3.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "trunk_lean",
          "message_en": "Too much lean — keep the chest up.",
          "message_th": "ลำตัวเอนมากเกินไป ยกอกขึ้น"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": 2.0,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": [
        {
          "metric": "knee_valgus",
          "as_key": "pose.stepdown_knee_valgus",
          "rep_aggregate": "peak",
          "set_aggregate": "median",
          "unit": "deg"
        }
      ]
    }
  },
  {
    "id": 17,
    "key": "side_plank",
    "name_en": "Side plank",
    "name_th": "แพลงก์ด้านข้าง",
    "category": "strength",
    "cue_en": "Straight line from ear to ankle, hips high.",
    "cue_th": "ลำตัวเป็นเส้นตรงจากหูถึงข้อเท้า ยกสะโพกสูง",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "hold",
      "view": "front",
      "enforce_view": true,
      "space": "image",
      "use_z": true,
      "detection": null,
      "targets": [
        {
          "metric": "hip_flexion",
          "aggregate": "peak",
          "min": null,
          "max": 20.0,
          "tolerance": 6.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "hip_sag",
          "message_en": "Hips dropping — push them up.",
          "message_th": "สะโพกตก ดันขึ้น"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": null,
      "tempo_max_s": null,
      "hold_target_s": 30.0,
      "emit": []
    }
  },
  {
    "id": 18,
    "key": "pogo_hops",
    "name_en": "Pogo hops",
    "name_th": "กระโดดสปริงข้อเท้า",
    "category": "plyo",
    "cue_en": "Fast, springy hops off the ankles. Knees stay fairly stiff.",
    "cue_th": "กระโดดถี่ๆ ใช้ข้อเท้าสปริง เข่าเกือบตรง",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "rep",
      "view": "front",
      "enforce_view": true,
      "space": "image",
      "use_z": true,
      "detection": {
        "signal": "knee_flexion",
        "enter": 18.0,
        "exit": 8.0,
        "min_duration_s": 0.12,
        "max_duration_s": 2.0,
        "min_amplitude": 5.0
      },
      "targets": [
        {
          "metric": "knee_flexion",
          "aggregate": "peak",
          "min": null,
          "max": 45.0,
          "tolerance": 8.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "too_much_knee",
          "message_en": "Bounce off the ankles, not the knees.",
          "message_th": "ใช้ข้อเท้าสปริง ไม่ใช่ย่อเข่า"
        },
        {
          "metric": "knee_valgus",
          "aggregate": "peak",
          "min": null,
          "max": 10.0,
          "tolerance": 2.0,
          "weight": 2.0,
          "critical": false,
          "judge": "worst",
          "code": "knee_valgus",
          "message_en": "Knee is collapsing inward — push it out over the middle toes.",
          "message_th": "เข่าบิดเข้าด้านใน ดันเข่าออกให้อยู่แนวนิ้วเท้ากลาง"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": null,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": []
    }
  },
  {
    "id": 19,
    "key": "spanish_squat",
    "name_en": "Spanish squat (isometric hold)",
    "name_th": "สแปนิชสควอทค้างไว้",
    "category": "strength",
    "cue_en": "Sit back against a band at knee height, shins vertical, hold.",
    "cue_th": "ย่อตัวโดยมียางยืดคล้องใต้เข่า หน้าแข้งตั้งฉาก แล้วค้างไว้",
    "equipment": "strong resistance band anchored at knee height",
    "demo_url": null,
    "pose_rule": {
      "mode": "hold",
      "view": "side",
      "enforce_view": true,
      "space": "image",
      "use_z": false,
      "detection": null,
      "targets": [
        {
          "metric": "knee_flexion",
          "aggregate": "mean",
          "min": 60.0,
          "max": 95.0,
          "tolerance": 8.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "knee_angle_off",
          "message_en": "Aim for roughly 70-80 degrees at the knee.",
          "message_th": "ให้มุมเข่าประมาณ 70-80 องศา"
        },
        {
          "metric": "trunk_lean",
          "aggregate": "peak",
          "min": null,
          "max": 25.0,
          "tolerance": 6.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "trunk_lean",
          "message_en": "Keep the chest up and the shins vertical.",
          "message_th": "ยกอกขึ้น และให้หน้าแข้งตั้งฉาก"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": null,
      "tempo_max_s": null,
      "hold_target_s": 45.0,
      "emit": [
        {
          "metric": "hold_seconds",
          "as_key": "pose.spanish_squat_hold",
          "rep_aggregate": "max",
          "set_aggregate": "max",
          "unit": "s"
        }
      ]
    }
  },
  {
    "id": 20,
    "key": "decline_squat",
    "name_en": "Single-leg decline squat",
    "name_th": "สควอทขาเดียวบนพื้นเอียง",
    "category": "strength",
    "cue_en": "On a decline board, lower slowly on one leg. Some tendon pain is fine.",
    "cue_th": "ยืนบนแผ่นเอียง ย่อขาเดียวลงช้าๆ ปวดเอ็นเล็กน้อยได้",
    "equipment": "25 degree decline board",
    "demo_url": null,
    "pose_rule": {
      "mode": "rep",
      "view": "side",
      "enforce_view": true,
      "space": "image",
      "use_z": false,
      "detection": {
        "signal": "knee_flexion",
        "enter": 25.0,
        "exit": 12.0,
        "min_duration_s": 0.35,
        "max_duration_s": 20.0,
        "min_amplitude": 18.0
      },
      "targets": [
        {
          "metric": "knee_flexion",
          "aggregate": "peak",
          "min": 55.0,
          "max": null,
          "tolerance": 6.0,
          "weight": 1.5,
          "critical": false,
          "judge": "worst",
          "code": "depth_insufficient",
          "message_en": "Lower further — the tendon needs the range.",
          "message_th": "ย่อลงให้ลึกขึ้น เอ็นต้องการช่วงการเคลื่อนไหวนี้"
        },
        {
          "metric": "trunk_lean",
          "aggregate": "peak",
          "min": null,
          "max": 22.0,
          "tolerance": 5.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "trunk_lean",
          "message_en": "Too much lean — that shifts load off the tendon.",
          "message_th": "เอนตัวมากเกินไป ทำให้แรงไม่ลงที่เอ็น"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": 3.0,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": [
        {
          "metric": "knee_flexion",
          "as_key": "pose.decline_squat_depth",
          "rep_aggregate": "peak",
          "set_aggregate": "median",
          "unit": "deg"
        }
      ]
    }
  },
  {
    "id": 22,
    "key": "single_leg_hop_landing",
    "name_en": "Single-leg hop and stick",
    "name_th": "กระโดดขาเดียวและหยุดนิ่ง",
    "category": "plyo",
    "cue_en": "Hop forward and stick the landing for two seconds without wobbling.",
    "cue_th": "กระโดดไปข้างหน้าแล้วลงน้ำหนักค้างไว้ 2 วินาที ห้ามเซ",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "rep",
      "view": "front",
      "enforce_view": true,
      "space": "image",
      "use_z": true,
      "detection": {
        "signal": "knee_flexion",
        "enter": 20.0,
        "exit": 10.0,
        "min_duration_s": 0.2,
        "max_duration_s": 20.0,
        "min_amplitude": 12.0
      },
      "targets": [
        {
          "metric": "knee_flexion",
          "aggregate": "peak",
          "min": 45.0,
          "max": null,
          "tolerance": 6.0,
          "weight": 1.5,
          "critical": false,
          "judge": "worst",
          "code": "stiff_landing",
          "message_en": "Absorb the landing — bend the knee more.",
          "message_th": "ซับแรงตอนลง งอเข่าให้มากขึ้น"
        },
        {
          "metric": "knee_valgus",
          "aggregate": "peak",
          "min": null,
          "max": 8.0,
          "tolerance": 2.0,
          "weight": 2.0,
          "critical": true,
          "judge": "worst",
          "code": "knee_valgus",
          "message_en": "Knee is collapsing inward — push it out over the middle toes.",
          "message_th": "เข่าบิดเข้าด้านใน ดันเข่าออกให้อยู่แนวนิ้วเท้ากลาง"
        },
        {
          "metric": "trunk_lean",
          "aggregate": "peak",
          "min": null,
          "max": 18.0,
          "tolerance": 3.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "trunk_lean",
          "message_en": "Too much lean — keep the chest up.",
          "message_th": "ลำตัวเอนมากเกินไป ยกอกขึ้น"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": null,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": [
        {
          "metric": "knee_valgus",
          "as_key": "pose.landing_knee_valgus",
          "rep_aggregate": "peak",
          "set_aggregate": "median",
          "unit": "deg"
        },
        {
          "metric": "knee_flexion",
          "as_key": "pose.landing_knee_flexion",
          "rep_aggregate": "peak",
          "set_aggregate": "median",
          "unit": "deg"
        }
      ]
    }
  },
  {
    "id": 23,
    "key": "lateral_bound",
    "name_en": "Lateral bound and stick",
    "name_th": "กระโดดออกข้างและหยุดนิ่ง",
    "category": "plyo",
    "cue_en": "Push sideways off one leg, land on the other and hold.",
    "cue_th": "ถีบออกด้านข้างด้วยขาหนึ่ง ลงอีกขาแล้วค้างไว้",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "rep",
      "view": "front",
      "enforce_view": true,
      "space": "image",
      "use_z": true,
      "detection": {
        "signal": "knee_flexion",
        "enter": 22.0,
        "exit": 10.0,
        "min_duration_s": 0.2,
        "max_duration_s": 20.0,
        "min_amplitude": 12.0
      },
      "targets": [
        {
          "metric": "knee_flexion",
          "aggregate": "peak",
          "min": 40.0,
          "max": null,
          "tolerance": 6.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "stiff_landing",
          "message_en": "Bend the knee to absorb the landing.",
          "message_th": "งอเข่าเพื่อซับแรงตอนลง"
        },
        {
          "metric": "knee_valgus",
          "aggregate": "peak",
          "min": null,
          "max": 8.0,
          "tolerance": 2.0,
          "weight": 2.0,
          "critical": true,
          "judge": "worst",
          "code": "knee_valgus",
          "message_en": "Knee is collapsing inward — push it out over the middle toes.",
          "message_th": "เข่าบิดเข้าด้านใน ดันเข่าออกให้อยู่แนวนิ้วเท้ากลาง"
        },
        {
          "metric": "pelvic_drop",
          "aggregate": "peak",
          "min": null,
          "max": 7.0,
          "tolerance": 1.5,
          "weight": 1.5,
          "critical": false,
          "judge": "worst",
          "code": "pelvic_drop",
          "message_en": "Hip is dropping on the other side — keep the pelvis level.",
          "message_th": "สะโพกอีกข้างตก พยายามรักษาระดับเชิงกรานให้ตรง"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": null,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": [
        {
          "metric": "knee_valgus",
          "as_key": "pose.landing_knee_valgus",
          "rep_aggregate": "peak",
          "set_aggregate": "median",
          "unit": "deg"
        }
      ]
    }
  },
  {
    "id": 30,
    "key": "heading_jump",
    "name_en": "Two-footed heading jump",
    "name_th": "กระโดดโหม่งสองเท้า",
    "category": "plyo",
    "cue_en": "Jump, head an imaginary ball, land soft on both feet.",
    "cue_th": "กระโดดโหม่งลูกสมมติ ลงพื้นสองเท้าแบบนุ่มนวล",
    "equipment": null,
    "demo_url": null,
    "pose_rule": {
      "mode": "rep",
      "view": "front",
      "enforce_view": true,
      "space": "image",
      "use_z": true,
      "detection": {
        "signal": "knee_flexion",
        "enter": 25.0,
        "exit": 12.0,
        "min_duration_s": 0.25,
        "max_duration_s": 20.0,
        "min_amplitude": 15.0
      },
      "targets": [
        {
          "metric": "knee_flexion",
          "aggregate": "peak",
          "min": 45.0,
          "max": null,
          "tolerance": 8.0,
          "weight": 1.0,
          "critical": false,
          "judge": "worst",
          "code": "stiff_landing",
          "message_en": "Land softer — bend the knees.",
          "message_th": "ลงพื้นให้นุ่มขึ้น งอเข่า"
        },
        {
          "metric": "knee_valgus",
          "aggregate": "peak",
          "min": null,
          "max": 10.0,
          "tolerance": 2.0,
          "weight": 2.0,
          "critical": true,
          "judge": "worst",
          "code": "knee_valgus",
          "message_en": "Knee is collapsing inward — push it out over the middle toes.",
          "message_th": "เข่าบิดเข้าด้านใน ดันเข่าออกให้อยู่แนวนิ้วเท้ากลาง"
        }
      ],
      "required_landmarks": [
        "LEFT_HIP",
        "RIGHT_HIP",
        "LEFT_KNEE",
        "RIGHT_KNEE",
        "LEFT_ANKLE",
        "RIGHT_ANKLE"
      ],
      "min_visibility": 0.5,
      "min_tracking_quality": 0.55,
      "smoothing_window": 5,
      "tempo_min_s": null,
      "tempo_max_s": null,
      "hold_target_s": null,
      "emit": []
    }
  }
] as unknown as Exercise[];
